### ISSUE TITLE
mysql driver 在建表之前查询

### ISSUE THREAD

**Issue by Anillc** [cosmotype/cosmotype#1]
<https://github.com/cosmotype/cosmotype/blob/292e1b06c651b5ee810b88050d80ad27cddfa6f3/packages/mysql/src/index.ts#L227>
在这个位置会断开执行，于是在别的地方使用 get 将会添加语句到队列中，随后 await 结束后才会将创建表的语句添加到队列中，导致建表前执行查询。也许应该标志一下 prepare 还没有完成，等到完成之后才能添加队列

**Comment by Shigma** [comment]
更新一下 cosmotype 版本看看还有无此问题？

**Comment by Anillc** [comment]
没问题了
